# Module manifest for module 'Abacus-ScriptSigning'
# Generated by: adm-cbrennan

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Abacus-ScriptSigning.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# ID used to uniquely identify this module
GUID = '125ba55a-b3fb-417c-9886-5fafa5ea3c88'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
   'abacus-logging',
   'abacus-secret',
   'abacus-sql'
   )


 # Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @( )

FunctionsToExport = '*'
CmdletsToExport   = '*'
VariablesToExport = '*'
AliasesToExport   = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

}