# Module manifest for module 'Abacus-SQL'
# Generated by: adm-cbrennan
# Generated on: 3/30/2020

@{
# Script module or binary module file associated with this manifest.
RootModule = 'Abacus-SQL.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# ID used to uniquely identify this module
GUID = 'f68844b8-0449-4135-b4e2-b61bc778ea63'

# Modules that must be imported into the global environment prior to importing this module
 RequiredModules = @(
    #'abacus-logging'
 )

 # Script files (.ps1) that are run in the caller's environment prior to importing this module.
 #ScriptsToProcess = @(   )

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

FunctionsToExport = '*'
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'

}