# Module manifest for module 'abacus-veeamreport'
# Generated by: Chris Brennan
# Generated on: 1/24/2020
@{
RootModule = 'Abacus-VeeamReport.psm1'
ModuleVersion = '1.0'
GUID = '67443cf7-dc00-42df-b498-d377cef75db7'
Author = 'Chris Brennan'
CompanyName = 'Abacus Group LLC'
Description = 'Generate Report of Servers without Veeam Restrore Points'

#PowerShellVersion = '5.1'
#PowerShellHostVersion = '5.0'
#DotNetFrameworkVersion = '4.2'
RequiredModules = @(
   'Abacus-SQL',
   'abacus-logging',
   'abacus-winops'
)
FunctionsToExport = '*'
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = @()
}

